# Generated by Django 5.2.5 on 2025-08-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_cart_items_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(default='', upload_to='restaurants/'),
        ),
    ]
