# Generated by Django 5.2.5 on 2025-08-30 17:24

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_restaurant_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=delivery.models.get_menu_item_image_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
